AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kurly admin backend
  SAM Template for kurly-admin-backend
Globals:
  Function:
    Timeout: 480

Parameters:
  CertificateArn:
    Type: String
    Default: arn:aws:acm:ap-northeast-2:948605357278:certificate/f619212b-90ae-4491-8683-cc949467d76e

Resources:

  KurlyAdminBackendApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Kurly Admin Web Application
      ApplicationName: kurly-admin-backend

  KurlyAdminBackendVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref KurlyAdminBackendApplication
      SourceBundle: ebpackage

  KurlyAdminBackendConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref KurlyAdminBackendApplication
      SolutionStackName: 64bit Amazon Linux 2 v3.3.1 running Corretto 11
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
        - Namespace: aws:elbv2:listener:443
          OptionName: DefaultProcess
          Value: default
        - Namespace: aws:elbv2:listener:443
          OptionName: Protocol
          Value: HTTPS
        - Namespace: aws:elbv2:listener:443
          OptionName: SSLCertificateArns
          Value: !Ref CertificateArn
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref KurlyAdminBackendInstanceRole
        - Namespace: aws:autoscaling:updatepolicy:rollingupdate
          OptionName: RollingUpdateEnabled
          Value: true

  KurlyAdminBackendEnv:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn: KurlyAdminBackendVersion
    Properties:
      ApplicationName: !Ref KurlyAdminBackendApplication
      TemplateName: !Ref KurlyAdminBackendConfigurationTemplate
      VersionLabel: !Ref KurlyAdminBackendVersion

  KurlyAdminBackendRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/CloudWatchEventsFullAccess

  KurlyAdminBackendInstanceRole:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref KurlyAdminBackendRole

  KurlyAdminBackendDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: metrichosu.net.
      Comment: Zone apex alias targeted to ALB of MetricHosu REST API
      RecordSets:
        - Name: backend.metrichosu.net.
          Type: CNAME
          TTL: 900
          ResourceRecords:
            - !GetAtt KurlyAdminBackendEnv.EndpointURL

Outputs:
  KurlyAdminBackendAddress:
    Description: "Kurly Admin REST API Address"
    Value: !Join
      - ", "
      - - !Sub
          - 'http://${EndpointURL}'
          - EndpointURL: !GetAtt KurlyAdminBackendEnv.EndpointURL
        - !Sub
          - 'https://${EndpointURL}'
          - EndpointURL: !GetAtt KurlyAdminBackendEnv.EndpointURL