spring:
  datasource:
    username: ${PUT_USERNAME_HERE}
    password: ${PUT_PASSWORD_HERE}
    url: ${PUT_URL_HERE}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

custom-variable:
  amazon:
    cloudwatch:
      namespace: "Custom Metric Demo"
  make-initial-data: false